In [15]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [7]:
df_final = pd.read_csv('../CleantFiles/final_data.csv', index_col = [0])

In [5]:
df_demo = pd.read_csv('demographic.csv', index_col = [0])
df_physical_og = pd.read_csv('physical_exam_og.csv', index_col = [0])
df_physical_translated = pd.read_csv('physical_exam_translated.csv', index_col = [0])
df_diabetes_stat = pd.read_csv('diabetes_stat_complete.csv', index_col = [0])
df_blood_mineral = pd.read_csv('blood_mineral_og.csv', index_col = [0])
df_blood_mineral_translated = pd.read_csv('blood_mineral_relabeled.csv', index_col = [0])
df_blood_nutrient = pd.read_csv('blood_nutrient_og.csv')

In [84]:
df_demo.drop(columns=['RaceNHA', 'PeopleFamily', 'HHIncome'], inplace=True)

og_race = ['NHA-NHBlack', 'NHA-NHWhite', 'NHA-MexAmerican', 'NHA-OtherHisp', 'Other', 'NHA-NHAsian']
cleaned_race = ['Black', 'White', 'Mexican American', 'Other Hispanic', 'Other', 'Asian']

count = 0
for race in og_race:
    df_demo.iloc[df_demo['RaceNHA'] == race, 3] = cleaned_race[count]
    count += 1

In [88]:
## Replace Unknown Variables

df_demo.iloc[(df_demo['Gender'] == 'Female') & (~df_demo['PregnancyStatus'].isin(['CannotTell', 'Unknown', 'NotPregnant','Pregnant'])), 9] = 'Unknown'
df_demo.iloc[df_demo['Gender'] == 'Male', 9] = 'NotApplicable'

df_demo.iloc[(~df_demo['Citizenship'].isin(['USCitizen','NonUSCitizen', 'Refused','DontKnow'])), 5] = 'Unknown'
df_demo.iloc[(~df_demo['USStayLength'].isin(['10-15','20-30','5-10','30-40','1-5','>50','40-50','15-20','DontKnow','Refused','<1'])), 6] = 'Unknown'
df_demo.iloc[(~df_demo['EduLevelAdult'].isin(['HighSchool/GED','College/AA','3Grade','College/Above', '9-11Grade', '2Grade' ,'4Grade', '9Grade', '>9Grade' ,'>HighSchool' ,'6Grade', '1Grade', '7Grade', '8Grade' ,'NoEdu/KG', '5Grade', '10Grade' ,'11Grade', 'HighSchool'
, '12Grade', 'GED' ,'>5Grade', 'DontKnow', 'Refused'])), 7] = 'Unknown'
df_demo.iloc[(~df_demo['MaritalStatus'].isin(['Separated', 'Married' , 'Divorced' ,'Widowed', 'NeverMarried' ,'LivingIn'
 ,'Refused', 'DontKnow'])), 8] = 'Unknown'


In [95]:
df_demo = df_demo.merge(df_diabetes_stat, on='SEQN', how='inner')

In [13]:
df_demo.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10175 entries, 1 to 10175
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   SEQN             10175 non-null  int64  
 1   Gender           10175 non-null  object 
 2   AgeYears         10175 non-null  float64
 3   Race             10175 non-null  object 
 4   RaceNHA          10175 non-null  object 
 5   BirthCountry     10175 non-null  object 
 6   Citizenship      10171 non-null  object 
 7   USStayLength     1908 non-null   object 
 8   EduLevelAdult    8572 non-null   object 
 9   MaritalStatus    5769 non-null   object 
 10  PregnancyStatus  1309 non-null   object 
 11  PeopleHH         10175 non-null  int64  
 12  PeopleFamily     10175 non-null  int64  
 13  HHIncome         10042 non-null  object 
 14  FamilyIncome     10052 non-null  object 
 15  PovertyRatio     9390 non-null   float64
dtypes: float64(2), int64(3), object(11)
memory usage: 1.3+ MB


In [10]:
for col in df_final.columns:
    print(col)
    print(df_final[col].unique())
    print('\n')

SEQN
[73557 73558 73559 ... 83729 83730 83731]


Gender
['Male' 'Female']


AgeYears
[69.  54.  72.   9.9 73.  56.   0.5 61.  65.  26.   9.1 76.  10.4 10.7
 33.   1.6 16.2 32.  18.2 12.2 38.  50.  23.   7.2 13.2 28.   4.8 14.5
 11.7 35.   2.5  6.3 29.   3.9 58.  57.  20.  13.4 37.  12.4  4.1 16.6
 75.   3.2 43.   3.6 60.  55.  62.   6.6 36.   3.8 80.  31.   0.1 13.8
  4.2  1.9  2.1 63.  71.  67.  64.   8.6  4.3 16.7  6.4  6.2 10.3 46.
 44.  19.5 70.  59.  25.  39.   5.2 24.  30.  49.  45.  51.  12.6  9.8
  2.8  7.7  8.2 77.  14.2 78.  66.   8.3  0.9 47.  48.   8.7  5.6 18.7
  3.3 53.  11.8  3.7 16.3 12.8  5.5 11.2  0.8  7.3  9.2  8.9 11.5 15.8
 15.7 17.8  4.   4.7 42.   0.4 21.  14.9 68.  18.1 10.9  6.5  6.  11.1
 10.8 52.   5.8 34.   0.3  0.6  4.4  7.6 13.7  9.3  2.3 13.6 12.1 40.
  1.1  2.7  7.  15.3 15.2 17.5  5.9 19.3  4.9 17.3 12.5  8.1  0.2 14.8
 27.   4.6  3.4 41.   6.7  7.8  2.6  1.8 16.5  5.7  7.9 17.   7.1 11.4
 11.  13.5 18.4  5.3  0.7  8.  17.6  2.2 22.  19.2 19.9 10.6 12.3


DR1TPOTA
[2228.   4930.   1694.   ... 2525.63 5269.   4438.  ]


DR1TPROT
[ 43.63 338.13  64.61 ... 223.32  47.55  96.06]


DR1TTFAT
[ 52.81 124.29  65.97 ... 193.51 110.3   78.63]


DR1TTHEO
[3.600e+01 0.000e+00 7.100e+01 3.070e+01 6.700e+01 1.100e+01 7.500e+01
 2.600e+01 8.500e+01 2.738e+01 2.500e+01 1.210e+02 2.000e+00 2.864e+01
 1.000e+01 1.200e+01 8.700e+01 2.000e+01 9.000e+01 2.866e+01 2.330e+02
 4.500e+01 5.200e+01 4.300e+01 1.400e+01 1.500e+01 2.700e+01 2.100e+01
 1.900e+02 7.000e+00 6.100e+01 3.114e+01 3.039e+01 2.400e+01 3.700e+01
 3.100e+01 3.300e+01 9.000e+00 5.600e+01 2.836e+01 8.000e+00 5.500e+01
 1.000e+02 8.800e+01 3.420e+01 1.010e+02 3.367e+01 2.370e+02 6.000e+00
 5.700e+01 3.225e+01 3.259e+01 3.900e+01 5.000e+00 1.700e+01 3.065e+01
 3.000e+00 4.800e+01 1.300e+01 3.127e+01 1.110e+02 1.600e+01 3.330e+01
 5.100e+01 2.820e+02 3.780e+02 9.700e+01 2.790e+02 7.300e+01 1.460e+02
 1.050e+02 1.900e+01 9.200e+01 1.660e+02 3.000e+01 4.000e+00 2.793e+01
 1.960e+02 4.000e+01 2.150

In [14]:
df_blood_mineral.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9892 entries, 1:1 to 2:4425
Data columns (total 61 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   X            9892 non-null   int64  
 1   SEQN         9892 non-null   int64  
 2   LBXBCD       9892 non-null   float64
 3   LBXBPB       9892 non-null   float64
 4   LBXBMN       9892 non-null   float64
 5   LBXTHG       9892 non-null   float64
 6   LBXBSE       9892 non-null   float64
 7   LBXTC        9892 non-null   float64
 8   LBDLYMNO     9892 non-null   float64
 9   LBDMONO      9892 non-null   float64
 10  LBDNENO      9892 non-null   float64
 11  LBDEONO      9892 non-null   float64
 12  LBDBANO      9892 non-null   float64
 13  LBXRBCSI     9892 non-null   float64
 14  LBXHGB       9892 non-null   float64
 15  LBXPLTSI     9892 non-null   float64
 16  LBXGH        9892 non-null   float64
 17  LBXIN        9892 non-null   float64
 18  PHAFSTHR     9892 non-null   float64
 19  LBXGLT 